//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubtitlesApp.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainLabelTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainLabelTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubtitlesApp.Resources.Strings.MainLabelTexts", typeof(MainLabelTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare case when AI is actually useful.
        /// </summary>
        public static string AiUseful {
            get {
                return ResourceManager.GetString("AiUseful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcribe, translate, swipe in, swipe away, scroll and navigate.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language barrier is not a thing anymore.
        /// </summary>
        public static string LanguageBarrier {
            get {
                return ResourceManager.GetString("LanguageBarrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not just another API wrapper!.
        /// </summary>
        public static string NotWrapper {
            get {
                return ResourceManager.GetString("NotWrapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing special as a service.
        /// </summary>
        public static string Nsaas {
            get {
                return ResourceManager.GetString("Nsaas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app is free and open source. The APIs - not necessarily.
        /// </summary>
        public static string OpenSource {
            get {
                return ResourceManager.GetString("OpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing impressive. Just subtitles that don&apos;t get in your way.
        /// </summary>
        public static string Subtitles {
            get {
                return ResourceManager.GetString("Subtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version is newer than anything we&apos;ve ever released.
        /// </summary>
        public static string ThisVersion {
            get {
                return ResourceManager.GetString("ThisVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great tool for learning foreign languages.
        /// </summary>
        public static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcribe and translate any video.
        /// </summary>
        public static string TranscribeTranslate {
            get {
                return ResourceManager.GetString("TranscribeTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media transcription is largely solved.
        /// </summary>
        public static string TranscriptionSolved {
            get {
                return ResourceManager.GetString("TranscriptionSolved", resourceCulture);
            }
        }
    }
}
